logging:
  level: INFO

mongoHost : localhost
mongoPort : 27017
mongoDB : taskDB
adminCollectionName : admins
storeCollectionName : stores
subuserCollectionName : subusers
productCollectionName : products
collectionName : admins